"""Add active field to Subscription model

Revision ID: de031012504f
Revises: 19debe9d2aa6
Create Date: 2021-01-19 17:14:41.038438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de031012504f'
down_revision = '19debe9d2aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'active')
    # ### end Alembic commands ###
